### PR TITLE
_parseSEARCH: use binary search instead of Array.prototype.indexOf()

### PR DESCRIPTION
**Pull request by nifgraup**
Makes real difference when the SEARCH response has tens of thousands of numbers.

### CODE REVIEW

**Comment by andris9** [comment]
I tested this and using binary search function seems to be about 10%-30% faster (here's the [test script](https://gist.github.com/andris9/06f2b47a37a9f3d410330587e27d0b88#file-test-js-L6-L51) I used). The `binSearch` function itself is quite small and it probably never changes so maybe it would be better to include it in emailjs-imap-client code instead of loading it as an external dependency.

**Comment by nifgraup** [comment]
I ran your script and the speed improvement grows with the input size, as expected with the improved time complexity `O(n^2)` vs. `O(n*log(n))`. I wonder what can be assumed about the input: If `result.attributes` is always/generally ordered then once `binSearch` returns index position, it's better to try to continue to insert there while walking the rest of the array. That would get the time complexity down to `O(n)` for best case input.

Regarding inlining `binSearch`, that depends of how the project is organized. I use the `binary-search` npm module in other places so it's unnecessary to have two copies, but it's true that it is very small. Just as long as it get left alone since it's surprisingly tricky to implement correctly :).

**Comment by andris9** [comment]
emailjs-imap-client can run in many different runtimes and adding additional dependencies can be quite bothersome, so it's better to avoid it if possible. The binarySeatch module is CC0 licensed and most probably is never going to change, so we can safely copy the function declaration over and that would be it.

**Comment by felixhammerl** [comment]
i am with andris on this one. the problem is, the `require` part won't work, b/c the module is commonjs, not AMD... can you include it as a file?

**Pull request merged**
