### PR TITLE
Fix issues #147 and hopefully #143

### PR DESCRIPTION
**Pull request by rickhall**
Rewrite _iterateIncomingBuffer() to parse from the beginning of the buffer to the end in an attempt to make it easier to understand and to better cope with content handling while trying to chunk the server response into lines.

This addresses issue #147 for me. I don't know if it addresses the reported issue in #143, since I didn't report it, but I think it might. It does address the other similar issue that I reported in the comments of #143.

### CODE REVIEW

**Comment by rickhall** [comment]
Local test results:

```
$ npm run test

> emailjs-imap-client@2.0.8 test /Users/rickhall/Projects/emailjs-imap-client
> grunt

Running "jshint:all" (jshint) task
>> 9 files lint free.

Running "mochaTest:test" (mochaTest) task


  browserbox integration tests
    Connection tests
      ✓ should use STARTTLS by default (58ms)
      ✓ should ignore STARTTLS
      ✓ should fail connecting to non-STARTTLS host
      ✓ should connect to non secure host
    Post login tests
      #listMailboxes
        ✓ should succeed
      #listMessages
        ✓ should succeed
      #upload
        ✓ should succeed
      #search
        ✓ should return a sequence number
        ✓ should return an uid
        ✓ should work with complex queries
      #setFlags
        ✓ should set flags for a message
        ✓ should add flags to a message
        ✓ should remove flags from a message
        ✓ should not return anything on silent mode
      #store
        ✓ should add labels for a message
        ✓ should set labels for a message
        ✓ should remove labels from a message
      #deleteMessages
        ✓ should delete a message
      #copyMessages
        ✓ should copy a message
      #moveMessages
        ✓ should move a message
      precheck
        ✓ should handle precheck error correctly
        ✓ should select correct mailboxes in prechecks on concurrent calls
        ✓ should send precheck commands in correct order on concurrent calls
    Timeout
      ✓ should timeout
(node:27242) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: 24 Socket timed out!
(node:27242) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      ✓ should reject all pending commands on timeout

  browserbox imap unit tests
    #close
      ✓ should call socket.close
      ✓ should call socket.close
    #upgrade
      ✓ should upgrade socket
      ✓ should not upgrade socket
    #setHandler
      ✓ should set global handler for keyword
    #socket.onerror
      ✓ should emit error and close connection
    #socket.onclose
      ✓ should emit error 
    #_onData
      ✓ should process input
    #_iterateIncomingBuffer
      ✓ should ignore incomplete literals with line feeds
      ✓ should parse multiple zero-length literals
      ✓ should iterate chunked input
      ✓ should process chunked literals
      ✓ should process chunked literals 2
      ✓ should process chunked literals 3
      ✓ should process chunked literals 4
      ✓ should process CRLF literal
      ✓ should process CRLF literal 2
      ✓ should process two commands when CRLF arrives in 2 parts
      ✓ should process literal when literal count arrives in 2 parts
      ✓ should process literal when literal count arrives in 2 parts 2
      ✓ should process literal when literal count arrives in 2 parts 3
      ✓ should process literal when literal count arrives in 2 parts 4
      ✓ should process literal when literal count arrives in 3 parts
      ✓ should process SEARCH response when it arrives in 2 parts
      ✓ should not process {} in string as literal 1
      ✓ should not process {} in string as literal 2
    #_parseIncomingCommands
      ✓ should process a tagged item from the queue
      ✓ should process an untagged item from the queue
      ✓ should process a plus tagged item from the queue
      ✓ should process an XOAUTH2 error challenge
    #_handleResponse
      ✓ should invoke global handler by default
      ✓ should invoke global handler if needed
      ✓ should push to payload
      ✓ should invoke command callback
    #enqueueCommand
      ✓ should reject on NO/BAD
      ✓ should invoke sending
      ✓ should only queue
    #_sendRequest
      ✓ should enter idle if nothing is to process
      ✓ should send data
      ✓ should send partial data
      ✓ should run precheck
    #_enterIdle
      ✓ should set idle timer
    #_processResponse
      ✓ should set humanReadable
      ✓ should set response code
    #isError
      ✓ should detect if an object is an error
    #enableCompression
      ✓ should create inflater and deflater streams
    #getPreviouslyQueued
      ✓ should return undefined with empty queue and no current command
      ✓ should return undefined with empty queue and non-SELECT current command
      ✓ should return current command with empty queue and SELECT current command
      ✓ should return current command with non-SELECT commands in queue and SELECT current command
      ✓ should return last SELECT before ctx with multiple SELECT commands in queue (1)
      ✓ should return last SELECT before ctx with multiple SELECT commands in queue (2)
      ✓ should return last SELECT before ctx with multiple SELECT commands in queue (3)

  browserbox unit tests
    #_onIdle
      ✓ should call enterIdle
      ✓ should not call enterIdle
    #connect
      ✓ should connect
(node:27242) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error
      ✓ should fail to login
(node:27242) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
      ✓ should timeout
    #close
      ✓ should force-close
    #exec
      ✓ should send string command
      ✓ should update capability from response
    #enterIdle
      ✓ should periodically send NOOP if IDLE not supported
      ✓ should break IDLE after timeout
    #breakIdle
      ✓ should send DONE to socket
    #upgradeConnection
      ✓ should do nothing if already secured
      ✓ should do nothing if STARTTLS not available
      ✓ should run STARTTLS
    #updateCapability
      ✓ should do nothing if capability is set
      ✓ should run CAPABILITY if capability not set
      ✓ should force run CAPABILITY
      ✓ should do nothing if connection is not yet upgraded
    #listNamespaces
      ✓ should run NAMESPACE if supported
      ✓ should do nothing if not supported
    #compressConnection
      ✓ should run COMPRESS=DEFLATE if supported
      ✓ should do nothing if not supported
      ✓ should do nothing if not enabled
    #login
      ✓ should call LOGIN
      ✓ should call XOAUTH2
    #updateId
      ✓ should not nothing if not supported
      ✓ should send NIL
      ✓ should exhange ID values
    #listMailboxes
      ✓ should call LIST and LSUB in sequence
      ✓ should not die on NIL separators
    #createMailbox
      ✓ should call CREATE with a string payload
      ✓ should call mutf7 encode the argument
      ✓ should treat an ALREADYEXISTS response as success
    #listMessages
      ✓ should call FETCH
    #search
      ✓ should call SEARCH
    #upload
      ✓ should call APPEND with custom flag
      ✓ should call APPEND w/o flags
    #setFlags
      ✓ should call STORE
    #store
      ✓ should call STORE
    #deleteMessages
      ✓ should call UID EXPUNGE
      ✓ should call EXPUNGE
    #copyMessages
      ✓ should call COPY
    #moveMessages
      ✓ should call MOVE if supported
      ✓ should fallback to copy+expunge
    #_shouldSelectMailbox
      ✓ should return true when ctx is undefined
      ✓ should return true when a different path is queued
      ✓ should return false when the same path is queued
    #selectMailbox
      ✓ should run SELECT
      ✓ should run SELECT with CONDSTORE
      ✓ should emit onclosemailbox
      should emit onselectmailbox before selectMailbox is resolved
        ✓ when it returns a promise
        ✓ when it does not return a promise
    #hasCapability
      ✓ should detect existing capability
      ✓ should detect non existing capability
    #_untaggedOkHandler
      ✓ should update capability if present
    #_untaggedCapabilityHandler
      ✓ should update capability
    #_untaggedExistsHandler
      ✓ should emit onupdate
    #_untaggedExpungeHandler
      ✓ should emit onupdate
    #_untaggedFetchHandler
      ✓ should emit onupdate
    #_parseSELECT
      ✓ should parse a complete response
      ✓ should parse response with no modseq
      ✓ should parse response with read-only
      ✓ should parse response with NOMODSEQ flag
    #_parseNAMESPACE
      ✓ should not succeed for no namespace response
      ✓ should return single personal namespace
      ✓ should return single personal, single users, multiple shared
      ✓ should handle NIL namespace hierarchy delim
    #_buildFETCHCommand
      ✓ should build single ALL
      ✓ should build FETCH with uid
      ✓ should build FETCH with uid, envelope
      ✓ should build FETCH with modseq
      ✓ should build FETCH with section
      ✓ should build FETCH with section and list
      ✓ should build FETCH with 
      ✓ should build FETCH with partial
    #_parseFETCH
      ✓ should return values lowercase keys
      ✓ should merge multiple responses based on sequence number
    #_parseENVELOPE
      ✓ should parsed envelope object
    #_parseBODYSTRUCTURE
      ✓ should parse bodystructure object
      ✓ should parse bodystructure with unicode filename
    #_buildSEARCHCommand
      ✓ should compose a search command
      ✓ should compose an unicode search command
    #_parseSEARCH
      ✓ should parse SEARCH response
      ✓ should parse empty SEARCH response
    #_buildSTORECommand
      ✓ should compose a store command from an array
      ✓ should compose a store set flags command
      ✓ should compose a store add flags command
      ✓ should compose a store remove flags command
      ✓ should compose a store remove silent flags command
      ✓ should compose a uid store flags command
    #_changeState
      ✓ should set the state value
      ✓ should emit onclosemailbox if mailbox was closed
    #_ensurePath
      ✓ should create the path if not present
      ✓ should return existing path if possible
      ✓ should handle case insensitive Inbox
    #_checkSpecialUse
      ✓ should return a matching special use flag
      ✓ should fail for non-existent flag
      ✓ should fail for invalid flag
      ✓ should return special use flag if a matching name is found
      ✓ should prefer matching special use flag over a matching name
    #_buildXOAuth2Token
      ✓ should return base64 encoded XOAUTH2 token
    untagged updates
      ✓ should receive information about untagged exists
      ✓ should receive information about untagged expunge
      ✓ should receive information about untagged fetch


  182 passing (2s)


Done, without errors.
```

**Comment by rickhall** [comment]
Just a comment on my patch. I decided to simply create a single buffer out of all incoming data, since I think it makes things simpler. The only thing I didn't really like is that to do so, I had to take the incoming data and temporarily put it into an Uint8Array so that I could append it to the new complete buffer.

I couldn't find a way to append it directly into the new complete buffer, so that is sort of a waste of an allocation, but other than that it is fairly clean.

Also, I don't claim to be any kind of expert in the IMAP protocol, I took my lead from how the existing code was trying to chunk server response lines and just tried to make it smarter based on my understanding of what the content of the server response should be.

**Comment by nifgraup** [comment]
The wasted allocation and unneccressary copy operations of incrementally creating the buffer like that is rather problematic. Let's say the total size is 1MB and the buffers 4k, then the intermediate wasted allocation is 128MB. For 10MB attachment, that's 12G of allocation and unnecessary copy and GC.

**Comment by rickhall** [comment]
I was thinking about that some more. I think I could do it in a similar fashion as the old approach, where I use an array of buffers.

I could look into that and open a separate pull request to enhance this one. What do you think?

**Comment by nifgraup** [comment]
You got me thinking this could be structured more like a state machine, is that the direction you were thinking of taking this? I'm going to test an idea of a refactor, but I think your original pull request #148 is satisfactory to close this issue.

**Comment by rickhall** [comment]
Well, there is a state machine in there, but it has a little bit of parser sprinkled in there too, since it has to understand escaping and whatnot. So, it's a little bit of a hyrbid, but possibly could be made more pure. Certainly seems to work better for me too.

I have another version mostly working where I don't concat the buffers into a single buffer, but I need to resolve test case failure and then test it on real data.

I assume you mean to close #147.

**Comment by nifgraup** [comment]
Yes, #147. Feeding tokens to the parser would be best: it gets rid of double parsing and takes less memory than creating a buffer with the whole command.

**Comment by rickhall** [comment]
I agree that using my basic approach to directly parse the data as it comes in would be smarter than breaking it into chunks and parsing the chunks, since breaking it into chunks requires knowledge of how to parse it anyway. Not only would that help resource consumption, it would be a little more efficient too, since the current approach has to start over from scratch each time the buffer doesn't contain enough information for it to continue.

Regardless, I am going to submit a new pull request, which is an alternate version of this pull request, which does not do extra copying of the buffers.

**Comment by rickhall** [comment]
Ok, apparently git automatically adds my new commit to this pull request rather than letting me create another. Fine.

Despite what the CI failure says, all tests still pass for me locally and I have used the modified algorithm to sync 175k messages (minus attachments) without issue.

**Comment by rickhall** [comment]
I don't know if you are going to work on a refactor or not, but if that isn't going to happen soon, I think it would be helpful to apply this PR in the meantime, since the original code is fairly broken as the two new test cases demonstrate. Thanks.

**Comment by rickhall** [comment]
Any progress on this?

**Comment by nifgraup** [comment]
I pushed cb477365e9eea57f2d6588ec827b93fe2fff7b03 where _iterateIncomingBuffer handles the buffer explicitly as a state machine.

I also commited your zero-length literal test with it as that fixed #147. The other test wasn't set up correctly - ran appendIncomingBuffer twice in a row without calling iterator.next() in between - so I skipped it.

**Comment by rickhall** [comment]
First of all, thanks!

Regarding the second test case, it is not clear to me why appendIncomingBuffer needs to be interleaved with iterator.next(), since it is just setting up a data structure (i.e., an array of two buffers) which is a legal structure.

Regardless, that test is very important since it demonstrates the most egregious bug that was fixed by the pull request, so I'll try to reformulate it. I'll open a separate pull request for that, ok?

**Comment by nifgraup** [comment]
If you look at _onData you see that every time a buffer is pushed to this._incomingBuffers, it is processed in _iterateIncomingBuffer. Therefore the test doesn't describe a situation that can happen in real code. The test passes when it looks like this:
```
            it('should ignore incomplete literals with line feeds', () => {
                appendIncomingBuffer('* 1 FETCH (UID {1024}\r\nThis is a partial literal.');
                var iterator1 = client._iterateIncomingBuffer();
                expect(iterator1.next().value).to.be.undefined;
                appendIncomingBuffer('It should return undefined\r\nsince it is not complete.');
                var iterator2 = client._iterateIncomingBuffer();
                expect(iterator2.next().value).to.be.undefined;
            });

```

**Comment by rickhall** [comment]
Ok, I see what you are saying, but then I guess I don't know how to create a test case that fails then. If you look at #143, there is another more complicated test case in there, but it is still formulated incorrectly because I don't iterate after each append.

However, those three strings correspond to the incomingBuffers array that I saw in the wild when the parsing failed. Not sure if that helps, but that's all I have for now.

**Comment by nifgraup** [comment]
I see the same with those three strings when iterating after each push. Is it possible that it was something else that caused the issue?

**Comment by rickhall** [comment]
Yeah, I agree, if I iterate after each it doesn't give me an error either. But my point was, those strings represent the three entries in incomingBuffers when the parse failure occurred. I could attempt to go back and recreate with the old version, but I am fairly certain that the issue I described is what was happening (i.e., it was seeing a linefeed/carriage return in an incomplete buffer and thinking it was terminating the line).

Regardless, I'm testing the new version of my 175k messages right now and will see how that goes and will potentially go back and see if I can further pin down the error on the old version. Thanks.

**Comment by rickhall** [comment]
BTW, are you planning on doing a release?

**Comment by enovision** [comment]
I've have submitted a release request, but haven't heard anything back from GRAV.

**Comment by nifgraup** [comment]
The problem is already there in the first entry of _incomingBuffers, {3019}\n and not {3019}\r\n as the standard says it should be https://tools.ietf.org/html/rfc3501#page-85. Are the higher level emailjs libraries forgiving to this this kind of IMAP commands and parse these kind of literals?

**Comment by rickhall** [comment]
Sorry, that might have been a mistake in my translating the buffers to strings. In this case, the email server is Gmail, so I'm sure it's doing the right thing. My simplified example in the submitted test case demonstrated the same issue, but was properly formatted.

One thing I should point out, after some tests, I have not reproduced this error with master. However, if I add my submitted test case, then master does fail, but my patch didn't fail in that case, for what it's worth.

So, it is possible that your patch potentially prevents it from getting into that state in the wild.

**Comment by rickhall** [comment]
I edited my previous comment to fix the \r\n issues.

**Pull request closed without merging**
