### PR TITLE
fix regression in _checkSpecialUse

### PR DESCRIPTION
**Pull request by nifgraup**

### CODE REVIEW

**Comment by felixhammerl** [comment]
Can you explain what the problem here was? This was done this way intentionally, because special-use should override naming. Making a fallback might create unwanted side-effects. Also, I don't get the benefit of the added test... O.o

**Comment by asutherland** [comment]
As I read the patch and the test, the issue is that the presence of any flag will cause the naming heuristics to not be used.  In the case of the additional test case, the "Praht" (Trash in Estonian) folder should be detected by name as Trash by the regexp.  But once the trash folder has children in it, it gets the \HasChildren flag which breaks heuristics.

The refactoring of the loop improves the control flow so that the pseudocode is:
- Try and determined special use based on explicit special use flags.  If we locate one, mark the folder with the specialUse (identifying it as special use somehow) and specialUseFlag (identifying it as special use explicitly from flags) properties and return, skipping the name heuristic check.
- Run the name heuristic check given that we didn't find any indications based on special use.  This will possibly identify the folder using the specialUse property only.

This does seem like an improvement, especially since having \HasChildren break name detection seems incorrect.  It probably makes sense to add some comments for clarity and for anyone attempting to improve special use detection in the future.  (As I've raised in other issues there are some higher level issues that could be addressed in a variety of ways.)  Feel free to extract comments from my comment here or let me know if you'd like more specialized ones.

**Comment by nifgraup** [comment]
@felixhammerl:
I think @asutherland described the problem well, "the presence of any [non-special use] flag will cause the naming heuristics to not be used.". The added test triggers a failure and reverting 2eb5b6d makes them green again. Also, I just pushed another test to cover what you said, "special-use should override naming".

**Comment by felixhammerl** [comment]
@asutherland so we're good to go here?

**Comment by asutherland** [comment]
Yes, I think so.  Modulo whatever the Travis CI failure is/was?  But that seems unrelated to these changes?

**Comment by felixhammerl** [comment]
yes, that's unrelated.

**Comment by felixhammerl** [comment]
something way down in tcp-socket goes boom, will take a look at that later.

**Pull request merged**
